name: dartling
version: 2.0.1
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: dartling is a domain model framework
homepage: https://github.com/dzenanr/dartling
documentation: http://goo.gl/Fd08zZ
dependencies:
  unittest: any
