name: dartling
author: Dzenan Ridjanovic <dzenanr@gmail.com>
homepage: http://ondart.me/
version: 0.0.8
description:
  Dartling is a domain model framework.
dependencies:
  unittest:
    sdk: unittest
