name: dartling
version: 2.0.0
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: dartling is a domain model framework
homepage: https://github.com/dzenanr/dartling
environment:
  sdk: '>=0.8.10+8 <2.0.0'
sdk:
  sdk: '>=0.8.10+8 <2.0.0'
documentation: http://goo.gl/Fd08zZ
dependencies:
  unittest: '>0.10.1 <0.11.0'
