name: dartling
author: Dzenan Ridjanovic <dzenanr@gmail.com>
homepage: http://ondart.me/
version: 0.0.1
description: >
  Dartling is a domain model framework for web application prototypes.
dependencies:
  unittest:
    sdk: unittest
  