name: dartling
version: 2.0.0
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: dartling is a model-driven data framework for design and code generation of Dart models
homepage: https://github.com/dzenanr/dartling
documentation: http://goo.gl/Fd08zZ
dependencies:
  unittest: '>=0.11.5 <0.12.0'

