name: dartling
version: 2.0.1
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: dartling is a model-driven data framework for design, code generation and use of Dart models
homepage: https://github.com/dzenanr/dartling
documentation: http://goo.gl/Fd08zZ
environment:
  sdk: '>=1.9.3 <2.0.0'
dependencies:
  test: any


