name: dartling
version: 1.0.1
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: dartling is a domain model framework
homepage: http://ondart.me/
documentation: http://goo.gl/Fd08zZ
environment:
  sdk: '>=0.8.10+8 <2.0.0'
dependencies:
  unittest: '>=0.9.0 <0.10.0'
